from app.agents.state import AgentState, get_task, task_update
from app.models import TaskStatus
from app.services.llm_service import get_llm_service
from app.sandbox.workspace import Workspace
from app.agents.prompts import REPORTER_SYSTEM_PROMPT
from pathlib import Path
from git import Repo
import json


async def generate_report_node(state: AgentState) -> dict:
    """Generate the completion report, push changes, and create a PR."""
    llm = get_llm_service()
    task = get_task(state)
    workspace = Workspace(
        task_id=task.id,
        github_url=task.github_url,
        branch=task.branch,
    )
    workspace.work_dir = Path(state["workspace_path"])
    workspace.repo = Repo(str(workspace.work_dir))

    # Commit remaining changes
    await workspace.commit(f"[Metl] Complete: {task.prompt[:80]}")

    # Get diff summary
    diff_summary = await workspace.get_diff_summary()

    # Build report content
    report_context = f"""
{REPORTER_SYSTEM_PROMPT}

Task:
- Prompt: {task.prompt}
- Repository: {task.github_url}

Steps Completed: {len(state["step_results"])}
Results:
{json.dumps(state["step_results"], indent=2)[:3000]}

Git Diff Summary:
{diff_summary}
"""

    report_text = await llm.generate(report_context)
    
    # Parse structured report
    report_text_clean = report_text.replace("```json", "").replace("```", "").strip()
    try:
        report_data = json.loads(report_text_clean)
    except json.JSONDecodeError:
        report_data = {
            "summary": report_text[:1000],
            "files_created": [],
            "files_modified": [],
            "issues_found_and_fixed": sum(
                1 for r in state["step_results"] if r.get("type") == "fix"
            ),
        }

    # Push branch and create PR
    pr_body = f"""## Metl Agent - Autonomous Implementation

### Summary
{report_data.get('summary', task.prompt)}

### Changes
```
{diff_summary[:2000]}
```

### Resources Used
{json.dumps([r.model_dump() for r in state['resources_approved']], indent=2)}

### Steps Completed
{chr(10).join(f'- Step {i+1}: {r.get("description", "")[:100]}' for i, r in enumerate(state["step_results"]) if "description" in r)}

---
*Generated by Metl Autonomous Coding Agent*
"""

    try:
        await workspace.push()
        pr_url = await workspace.create_pr(
            title=f"[Metl] {task.prompt[:60]}",
            body=pr_body,
        )
    except Exception as e:
        pr_url = None

    report = {
        "task_id": task.id,
        "status": "completed",
        "github_pr_url": pr_url,
        "github_branch": workspace.branch_name,
        "git_diff_summary": diff_summary[:500],
        "files_created": report_data.get("files_created", []),
        "files_modified": report_data.get("files_modified", []),
        "resources_used": [r.get("name", "") for r in state["resources_approved"]],
        "env_vars_required": {},
        "preview_url": state.get("preview_url"),
        "issues_found_and_fixed": report_data.get("issues_found_and_fixed", 0),
        "steps_completed": len(state["step_results"]),
        "duration_seconds": 0,
        "summary": report_data.get("summary", task.prompt),
    }

    return {
        "report": report,
        "pr_url": pr_url,
        "task": task_update(state, status=TaskStatus.COMPLETED, report=report),
    }